import random

def guess_number():
    number = random.randint(1, 100)
    tries = 0

    print("Welcome to the Number Guessing Game! I'm thinking of a number between 1 and 100.")

    while True:
        guess = int(input("Take a guess: "))
        tries += 1

        if guess < number:
            print("Too low! Try again.")
        elif guess > number:
            print("Too high! Try again.")
        else:
            print(f"Congratulations! You guessed the number in {tries} tries.")
            break

if __name__ == "__main__":
    guess_number()
